use bellpepper_core::{ConstraintSystem, LinearCombination, SynthesisError};
use bellpepper_core::boolean::{AllocatedBit, Boolean};
use bellpepper_core::num::AllocatedNum;
use ff::Field;
use itertools::{chain, zip_eq};
use neptune::circuit2::Elt;
use neptune::hash_type::HashType;
use neptune::sponge::api::{IOPattern, SpongeAPI, SpongeOp};
use neptune::sponge::circuit::SpongeCircuit;
use neptune::sponge::vanilla::Mode::Simplex;
use neptune::sponge::vanilla::SpongeTrait;
use neptune::Strength;

use crate::gadgets::utils::{alloc_num_equals, alloc_zero, conditionally_select};
use crate::parafold::cycle_fold::circuit::AllocatedScalarMulAccumulator;
use crate::parafold::cycle_fold::nifs::circuit::AllocatedSecondaryRelaxedR1CSInstance;
use crate::parafold::nifs::circuit::AllocatedRelaxedR1CSInstance;
use crate::parafold::nifs::RelaxedR1CSInstance;
use crate::parafold::nivc::{
  AllocatedNIVCIO, NIVCIO, NIVCPoseidonConstants, NIVCStateInstance, NIVCUpdateProof,
};
use crate::parafold::transcript::circuit::AllocatedTranscript;
use crate::parafold::transcript::TranscriptConstants;
use crate::supernova::EnforcingStepCircuit;
use crate::traits::CurveCycleEquipped;

/// A representation of a NIVC state, where `io` represents the computations inputs and outputs,
/// and the `accs` are the accumulators for each step function that was used to produce this result.
#[derive(Debug, Clone)]
pub struct AllocatedNIVCState<E: CurveCycleEquipped> {
  io: AllocatedNIVCIO<E>,
  accs_hash: Vec<AllocatedNum<E::Scalar>>,
  acc_cf: AllocatedSecondaryRelaxedR1CSInstance<E>,
}

impl<E: CurveCycleEquipped> AllocatedNIVCState<E> {
  /// Loads a previously proved state from a proof of its correctness.
  pub fn from_proof<CS>(
    mut cs: CS,
    ro_consts: &TranscriptConstants<E::Scalar>,
    proof: NIVCUpdateProof<E>,
  ) -> Result<(Self, AllocatedNum<E::Scalar>), SynthesisError>
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let NIVCUpdateProof {
      transcript_prev,
      transcript_buffer,
      state,
      acc_prev,
      index_prev,
    } = proof;

    // Allocate inputs:
    // - previous transcript state
    // - previous output
    let transcript_prev =
      AllocatedNum::alloc_infallible(cs.namespace(|| "alloc transcript_prev"), || transcript_prev);
    let state = AllocatedNIVCState::alloc_unchecked(cs.namespace(|| "alloc state"), state);

    // Define the base case as transcript_prev == 0
    let is_base_case: Boolean = {
      let zero = alloc_zero(cs.namespace(|| "alloc zero"));
      Boolean::from(alloc_num_equals(
        cs.namespace(|| "transcript_prev == 0"),
        &transcript_prev,
        &zero,
      )?)
    };

    // Compute hash of inputs
    let state_hash = state.hash(cs.namespace(|| "state hash"))?;

    // Set the IO of the previous circuit
    let X_prev = [state_hash, transcript_prev];

    // Initialize the transcript with the previous IO, and load the contents generated by the prover.
    let mut transcript =
      AllocatedTranscript::new(ro_consts.clone(), X_prev.clone(), transcript_buffer);

    // Enforce that the current IO is trivial, i.e. io.in == io.out
    state.io.enforce_trivial(
      cs.namespace(|| "is_base_case => (io.in == io.out)"),
      &is_base_case,
    );

    // Enforce that the secondary curve circuit is trivial
    state.acc_cf.enforce_trivial(
      cs.namespace(|| "is_base_case => acc_cf.is_trivial"),
      &is_base_case,
    );

    // Initialize scalar mul accumulator for folding
    let mut acc_sm = AllocatedScalarMulAccumulator::new(state.acc_cf);

    // Update the set of accumulators with the fresh folding proof
    let accs_hash_next = Self::update_accs(
      cs.namespace(|| "update accs"),
      state.accs_hash,
      X_prev,
      acc_prev,
      index_prev,
      &is_base_case,
      &mut acc_sm,
      &mut transcript,
    )?;

    // Prove all scalar multiplication by updating the secondary curve accumulator
    let acc_cf_next = acc_sm.finalize(cs.namespace(|| "finalize acc_sm"), &mut transcript)?;

    // If this is the first iteration, then reset `acc_cf` to its default state since no scalar multiplications
    // were actually computed
    let acc_cf_next =
      acc_cf_next.select_default(cs.namespace(|| "enforce trivial acc_cf"), &is_base_case)?;

    // Finalize transcript, and return the compressed state
    let transcript_state = transcript.seal(cs.namespace(|| "transcript seal"))?;

    let state_next = Self {
      io: state.io,
      accs_hash: accs_hash_next,
      acc_cf: acc_cf_next,
    };
    Ok((state_next, transcript_state))
  }

  pub fn update_io<CS, SF>(
    &mut self,
    mut cs: CS,
    step_circuit: &SF,
  ) -> Result<Option<NIVCIO<E>>, SynthesisError>
  where
    CS: ConstraintSystem<E::Scalar>,
    SF: EnforcingStepCircuit<E::Scalar>,
  {
    // Run the step circuit
    let cs_step = &mut cs.namespace(|| "synthesize");

    let (pc_curr, z_curr) = (Some(&self.io.pc_out), self.io.z_out.as_slice());

    let (pc_next, z_next) = step_circuit.enforcing_synthesize(cs_step, pc_curr, z_curr)?;

    self.io.pc_out = pc_next.ok_or(SynthesisError::AssignmentMissing)?;
    self.io.z_out = z_next;

    Ok(self.io.to_native())
  }

  // pub fn merge<CS>(
  //   mut cs: CS,
  //   self_L: Self,
  //   self_R: Self,
  //   ro_consts: &TranscriptConstants<E::Scalar>,
  //   proof: NIVCMergeProof<E>,
  //   transcript: &mut AllocatedTranscript<E>,
  // ) -> Result<(Self, NIVCIO<E::Scalar>), SynthesisError>
  // where
  //   CS: ConstraintSystem<E::Scalar>,
  // {
  //   let mut acc_sm = AllocatedScalarMulAccumulator::new();
  //
  //   let Self {
  //     io: io_L,
  //     accs_hash: accs_hash_L,
  //     acc_cf: acc_cf_L,
  //   } = self_L;
  //   let Self {
  //     io: io_R,
  //     accs_hash: accs_hash_R,
  //     acc_cf: acc_cf_R,
  //   } = self_R;
  //
  //   let io = AllocatedNIVCIO::merge(cs.namespace(|| "io merge"), io_L, io_R);
  //
  //   // Load the preimages of the accumulators in each state
  //   let (accs_L, accs_R) = {
  //     let accs_L = Self::load_accs(
  //       cs.namespace(|| "load accs_R"),
  //       proof.accs_L,
  //       accs_hash_L,
  //       ro_consts,
  //     )?;
  //     let accs_R = Self::load_accs(
  //       cs.namespace(|| "load accs_R"),
  //       proof.accs_R,
  //       accs_hash_R,
  //       ro_consts,
  //     )?;
  //     (accs_L, accs_R)
  //   };
  //
  //   // Merge the two lists of accumulators and return their hashes
  //   let accs_hash = {
  //     let accs = AllocatedRelaxedR1CSInstance::merge_many(
  //       cs.namespace(|| "accs"),
  //       accs_L,
  //       accs_R,
  //       &mut acc_sm,
  //       proof.nivc_merge_proof,
  //       transcript,
  //     )?;
  //
  //     accs
  //       .into_iter()
  //       .map(|acc| acc.hash(cs.namespace(|| "hash acc"), ro_consts))
  //       .collect::<Result<Vec<_>, _>>()?
  //   };
  //
  //   // Merge the secondary curve accumulators
  //   let acc_cf = AllocatedSecondaryRelaxedR1CSInstance::merge(
  //     cs.namespace(|| "merge acc_cf"),
  //     acc_cf_L,
  //     acc_cf_R,
  //     proof.cf_merge_proof,
  //     transcript,
  //   )?;
  //
  //   // Prove all scalar multiplications by folding the result into the secondary curve accumulator
  //   let acc_cf = acc_sm.finalize(
  //     cs.namespace(|| "acc_sm finalize"),
  //     acc_cf,
  //     proof.sm_fold_proofs,
  //     transcript,
  //   )?;
  //   let state = Self {
  //     io,
  //     accs_hash,
  //     acc_cf,
  //   };
  //   let io = state.io.to_native()?;
  //
  //   Ok((state, io))
  // }

  pub fn inputize<CS>(&self, mut cs: CS) -> Result<(), SynthesisError>
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let hash = self.hash(cs.namespace(|| "hash state"))?;
    hash.inputize(cs.namespace(|| "inputize hash"))
  }

  pub fn alloc_unchecked<CS>(mut cs: CS, state: NIVCStateInstance<E>) -> Self
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let io = AllocatedNIVCIO::alloc(cs.namespace(|| "alloc io"), state.io);

    let accs_hash = state
      .accs
      .iter()
      .enumerate()
      .map(|(i, acc)| {
        let acc_hash = acc.hash();
        AllocatedNum::alloc_infallible(cs.namespace(|| format!("alloc acc_hash {i}")), || acc_hash)
      })
      .collect::<Vec<_>>();

    let acc_cf = AllocatedSecondaryRelaxedR1CSInstance::alloc_unchecked(
      cs.namespace(|| "alloc acc_cf"),
      state.acc_cf,
    );

    Self {
      io,
      accs_hash,
      acc_cf,
    }
  }

  pub fn hash<CS>(&self, mut cs: CS) -> Result<AllocatedNum<E::Scalar>, SynthesisError>
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let elements = self.as_preimage().into_iter().collect::<Vec<_>>();
    let num_absorbs = elements.len() as u32;
    let constants =
      NIVCPoseidonConstants::<E>::new_with_strength_and_type(Strength::Standard, HashType::Sponge);

    let pattern = IOPattern(vec![SpongeOp::Absorb(num_absorbs), SpongeOp::Squeeze(1u32)]);
    let acc = &mut cs.namespace(|| "squeeze");
    let mut sponge = SpongeCircuit::new_with_constants(&constants, Simplex);
    sponge.start(pattern, None, acc);
    SpongeAPI::absorb(&mut sponge, num_absorbs, &elements, acc);
    let state_out = SpongeAPI::squeeze(&mut sponge, 1, acc);
    SpongeAPI::finish(&mut sponge, acc).expect("no error");
    state_out[0].ensure_allocated(acc, true)
  }

  fn update_accs<CS>(
    mut cs: CS,
    accs_hash: Vec<AllocatedNum<E::Scalar>>,
    X_prev: [AllocatedNum<E::Scalar>; 2],
    acc_prev: RelaxedR1CSInstance<E>,
    index_prev: Option<usize>,
    is_base_case: &Boolean,
    acc_sm: &mut AllocatedScalarMulAccumulator<E>,
    transcript: &mut AllocatedTranscript<E>,
  ) -> Result<Vec<AllocatedNum<E::Scalar>>, SynthesisError>
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let (acc_prev_hash, acc_curr_hash) = {
      // Load pre-image of accumulator to be updated
      let acc_prev =
        AllocatedRelaxedR1CSInstance::alloc(cs.namespace(|| "alloc acc_prev"), acc_prev);

      // Compute its hash
      let acc_prev_hash = acc_prev.hash(cs.namespace(|| "hash acc_prev"))?;

      // Set the R1CS IO as the transcript init followed by the state

      let acc_curr = acc_prev.fold(cs.namespace(|| "fold"), X_prev, acc_sm, transcript)?;

      let acc_curr_hash = acc_curr.hash(cs.namespace(|| "hash acc_curr"))?;

      (acc_prev_hash, acc_curr_hash)
    };

    // Create selector for acc_prev_hash and ensure it is contained in accs_hash
    let accs_hash_selector = {
      let bits = accs_hash
        .iter()
        .enumerate()
        .map(|(i, acc_hash)| {
          // Allocate a bit which is true if i == index_prev
          let bit = index_prev.map_or(false, |index_prev| index_prev == i);
          let bit = AllocatedBit::alloc(cs.namespace(|| format!("alloc selector[{i}]")), Some(bit))
            .unwrap();

          // Ensure acc_hash[index_prev] = acc_prev_hash
          cs.enforce(
            || format!("bit[{i}] * (acc_hash[{i}] - acc_prev_hash[{i}]) = 0"),
            |lc| lc + bit.get_variable(),
            |lc| lc + acc_hash.get_variable() - acc_prev_hash.get_variable(),
            |lc| lc,
          );

          Boolean::Is(bit)
        })
        .collect::<Vec<_>>();

      // Compute sum of all bits
      let lc_sum = bits.iter().fold(LinearCombination::zero(), |lc, bit| {
        lc + &bit.lc(CS::one(), E::Scalar::ONE)
      });

      // Ensure only 1 selection bit is true, except in the base case where all bits are 0
      cs.enforce(
        || "is_base.not = ∑_i bits[i]",
        |lc| lc,
        |lc| lc,
        |_| is_base_case.not().lc(CS::one(), E::Scalar::ONE) - &lc_sum,
      );

      bits
    };

    // Update hashes of accumulators in state
    zip_eq(accs_hash.into_iter(), accs_hash_selector.iter())
      .enumerate()
      .map(|(i, (acc_hash, bit))| {
        conditionally_select(
          cs.namespace(|| format!("accs_hash_curr {i}")),
          &acc_curr_hash,
          &acc_hash,
          bit,
        )
      })
      .collect::<Result<Vec<_>, _>>()
  }

  pub fn as_preimage(&self) -> impl IntoIterator<Item = Elt<E::Scalar>> + '_ {
    chain![
      self.io.as_preimage(),
      self.accs_hash.iter().cloned().map(Elt::Allocated),
      self.acc_cf.as_preimage()
    ]
  }

  #[allow(unused)]
  pub fn eq_native(&self, other: &NIVCStateInstance<E>) -> Option<bool> {
    for (lhs, acc) in zip_eq(&self.accs_hash, &other.accs) {
      let rhs = acc.hash();
      if lhs.get_value()? != rhs {
        return Some(false);
      }
    }

    if !self.io.eq_native(&other.io)? {
      return Some(false);
    }

    if !self.acc_cf.eq_native(&other.acc_cf)? {
      return Some(false);
    }

    Some(true)
  }

  // fn load_accs<CS>(
  //   mut cs: CS,
  //   accs_native: Vec<RelaxedR1CSInstance<E>>,
  //   accs_hash: Vec<AllocatedNum<E::Scalar>>,
  // ) -> Result<Vec<AllocatedRelaxedR1CSInstance<E>>, SynthesisError>
  // where
  //   CS: ConstraintSystem<E::Scalar>,
  // {
  //   zip_eq(accs_native, accs_hash)
  //     .map(
  //       |(acc_native, acc_hash): (RelaxedR1CSInstance<E>, AllocatedNum<E::Scalar>)| {
  //         let acc = AllocatedRelaxedR1CSInstance::alloc(cs.namespace(|| "alloc acc"), acc_native);
  //         let acc_hash_real = acc.hash(cs.namespace(|| "hash acc"))?;
  //
  //         // Ensure the loaded accumulator's hash matches the one from the state
  //         cs.enforce(
  //           || "acc_hash_real == acc_hash",
  //           |lc| lc,
  //           |lc| lc,
  //           |lc| lc + acc_hash_real.get_variable() - acc_hash.get_variable(),
  //         );
  //         Ok::<_, SynthesisError>(acc)
  //       },
  //     )
  //     .collect::<Result<Vec<_>, _>>()
  // }
}

impl<E: CurveCycleEquipped> AllocatedNIVCIO<E> {
  // pub fn merge<CS>(mut cs: CS, io_L: Self, io_R: Self) -> Self
  // where
  //   CS: ConstraintSystem<F>,
  // {
  //   // io_L.pc_out = io_R.pc_in
  //   cs.enforce(
  //     || "io_L.pc_out = io_R.pc_in",
  //     |lc| lc,
  //     |lc| lc,
  //     |lc| lc + io_L.pc_out.get_variable() - io_R.pc_in.get_variable(),
  //   );
  //
  //   // io_L.z_out = io_R.z_in
  //   zip_eq(&io_L.z_out, &io_R.z_in)
  //     .enumerate()
  //     .for_each(|(i, (z_L_i, z_R_i))| {
  //       cs.enforce(
  //         || format!("io_L.z_out[{i}] = io_R.z_in[{i}]"),
  //         |lc| lc,
  //         |lc| lc,
  //         |lc| lc + z_L_i.get_variable() - z_R_i.get_variable(),
  //       );
  //     });
  //
  //   Self {
  //     pc_in: io_L.pc_in,
  //     z_in: io_L.z_in,
  //     pc_out: io_R.pc_out,
  //     z_out: io_R.z_out,
  //   }
  // }

  pub fn enforce_trivial<CS>(&self, mut cs: CS, is_trivial: &Boolean)
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let is_trivial = is_trivial.lc(CS::one(), E::Scalar::ONE);

    // (is_trivial) * (z_in - z_out) = 0
    zip_eq(&self.z_in, &self.z_out)
      .enumerate()
      .for_each(|(i, (z_in_i, z_out_i))| {
        cs.enforce(
          || format!("(is_trivial) * (z_in[{i}] - z_out[{i}]) = 0"),
          |_| is_trivial.clone(),
          |lc| lc + z_in_i.get_variable() - z_out_i.get_variable(),
          |lc| lc,
        );
      });

    // (is_trivial) * (pc_in - pc_out) = 0
    cs.enforce(
      || "(is_trivial) * (pc_in - pc_out) = 0",
      |_| is_trivial,
      |lc| lc + self.pc_in.get_variable() - self.pc_out.get_variable(),
      |lc| lc,
    );
  }

  pub fn as_preimage(&self) -> impl IntoIterator<Item = Elt<E::Scalar>> + '_ {
    chain![
      [self.pc_in.clone()],
      self.z_in.iter().cloned(),
      [self.pc_out.clone()],
      self.z_out.iter().cloned()
    ]
    .map(Elt::Allocated)
  }

  pub fn alloc<CS>(mut cs: CS, state: NIVCIO<E>) -> Self
  where
    CS: ConstraintSystem<E::Scalar>,
  {
    let NIVCIO {
      pc_in,
      z_in,
      pc_out,
      z_out,
    } = state;

    let pc_in = AllocatedNum::alloc_infallible(cs.namespace(|| "alloc pc_in"), || pc_in);
    let z_in = z_in
      .into_iter()
      .enumerate()
      .map(|(i, z)| {
        AllocatedNum::alloc_infallible(cs.namespace(|| format!("alloc z_in[{i}]")), || z)
      })
      .collect();
    let pc_out = AllocatedNum::alloc_infallible(cs.namespace(|| "alloc pc_out"), || pc_out);
    let z_out = z_out
      .into_iter()
      .enumerate()
      .map(|(i, z)| {
        AllocatedNum::alloc_infallible(cs.namespace(|| format!("alloc z_out[{i}]")), || z)
      })
      .collect();

    Self {
      pc_in,
      z_in,
      pc_out,
      z_out,
    }
  }

  /// Attempt to extract the native representation.
  pub fn to_native(&self) -> Option<NIVCIO<E>> {
    let pc_in = self.pc_in.get_value()?;
    let z_in = self
      .z_in
      .iter()
      .map(|z| z.get_value())
      .collect::<Option<Vec<_>>>()?;
    let pc_out = self.pc_out.get_value()?;
    let z_out = self
      .z_out
      .iter()
      .map(|z| z.get_value())
      .collect::<Option<Vec<_>>>()?;
    Some(NIVCIO {
      pc_in,
      z_in,
      pc_out,
      z_out,
    })
  }
  
  pub fn eq_native(&self, other: &NIVCIO<E>) -> Option<bool> {
    let self_native = self.to_native()?;
    Some(&self_native == other)
  }
}
